### ISSUE TITLE
Link to parent theme strange

### ISSUE THREAD

**Issue by saschafrohwerk** [ryansommers/mercury#1]
Hi Ryan,
just tried out your theme. Looks great! One thing I noticed: The P2 theme is usually called P2 and is in the directory P2, not p2-wpcom. To get mercury running I had to change this in two lines of the style.css:
Template: p2-wpcom
@import url("../p2-wpcom/style.css");
must be only P2 in both cases.
Best regands, Sascha

**Comment by ryansommers** [comment]
Thanks Sascha! This issue is fixed in 1.0.2.
