### ISSUE TITLE
Problem connecting to the server

### ISSUE THREAD

**Issue by wesleyshaw** [ryansommers/mercury#2]
Beautiful theme. Thanks for sharing it. 

Testing today, and getting an error message when I try to do pretty much anything. No issues when using P2. 

![](https://dl.dropboxusercontent.com/s/nb1dhtd45cnr5xe/2014-06-27%20at%2012.01%20PM.png)

Any thoughts? Thanks. 

UPDATE: Disregard -- P2 now appears to be broken, too. Not your theme's fault. Weird.

**Comment by ryansommers** [comment]
Good to hear it wasn't Mercury. Did you manage to figure out what happened?

**Comment by wesleyshaw** [comment]
I'm not sure what triggered it, but the workaround was to resave my permalinks and now all is well with Mercury and P2. I'll let you know if I find other bugs, but for now, really nice work.
