### ISSUE TITLE
Link CSS issue

### ISSUE THREAD

**Issue by Fastidious** [ryansommers/mercury#4]
Note the double underline on hover, while not sign up, under Safari 7.0.6:

![Double line on hover](https://cloud.githubusercontent.com/assets/8352292/4272198/0bf34c20-3ce0-11e4-8121-7410e4a56e58.png)

**Comment by ryansommers** [comment]
What page are you seeing that on? I can't seem to recreate the situation that causes "Toggle Comments" to show. Are you seeing it on ryansommers.com/mercury ?

**Comment by Fastidious** [comment]
Yes, it happens on your test install, as well as mine. Toggle comments threads (collapse them) and then hover over "Toggle Comments" on a post that has comments.

**Comment by ryansommers** [comment]
Got it, all fixed.
